version: "3"

tasks:
  run:
    cmds:
      - go run -v ./...
  build:
    cmds:
      - go build -o bin -v ./...
  test:
    cmds:
      - go test -v ./...
  clean:
    cmds:
      - rm -rf bin/*
      - rm -rf data/*
